### PR TITLE
removed install chef/applications-service

### PR DESCRIPTION
**Pull request by anthonygrees**
Signed-off-by: anthonygrees <anthony_rees01@hotmail.com>

### CODE REVIEW

**Comment by ericcalabretta** [comment]
@anthonygrees This change is in Nicks PR too, I want to get it merged tomorrow but I had a question for Nick about his Terraform linting comment 

 https://github.com/chef-cft/national-parks-demo/pull/58/commits/a233344888729a5ebf540e0fc199402795418b9f

**Comment by niamhcahill** [comment]
I was going to test and merge this but based on @ericcalabretta 's comment, I'll wait until he asks Nick his question.

**Comment by ChefRycar** [comment]
For the historical record, I made the update to #58 when I was testing the TF12 updates. The only concern I had on review was that it looks like VSC's code linting hasn't caught up yet, and our stuff will generate some false positive warnings in the IDE. Not a dealbreaker, more an FYI. :-)

**Comment by ChefRycar** [comment]
This fix is now merged in with the TF 12 update. Thanks for the quick PR all the same @anthonygrees!

**Pull request closed without merging**
